#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Usage: common const
#

TWSE_STOCK_SUFFIX_TW = ".TW"  # 上市
TPEX_STOCK_SUFFIX_TWO = ".TWO"  # 上櫃
STOCK_DATA_FOLDER = "./web/stock_data/"
CSV_EXTENSION = ".csv"

# macd

OSC_RED_WEEK = "OSC 弱紅柱"
OSC_RED_STRONG = "OSC 強紅柱"
OSC_RED_CONSOLIDATION = "OSC 紅柱，趨勢不明，盤整中"

OSC_GREEN_WEEK = "OSC 弱綠柱"
OSC_GREEN_STRONG = "OSC 強綠柱"
OSC_GREEN_CONSOLIDATION = "OSC 綠柱，趨勢不明，盤整中"

MACD_ABOVE_MIDDLE = "macd零軸上"
MACD_BELOW_MIDDLE = "macd零軸下"

MACD_SHOW_UP_TREND = "MACD 上升趨勢"
MACD_SHOW_DOWN_TREND = "MACD 下降趨勢"

MACD_ABOUT_TO_CROSS_MIDDLE = "MACD 即將穿過零軸線"
MACD_BACKTEST_CROSS_MIDDLE = "MACD 穿過軸線的回測 N"

MACD_CLOSING_MIDDLE_FROM_BOTTOM = "MACD 從下方靠近軸線"
MACD_CLOSING_MIDDLE_FROM_ABOVE = "MACD 從上方靠近軸線"

# ma
CLOSING_TO_MA138_FROM_BOTTOM = "靠近138均線"
BACKTEST_CROSS_MA138 = "穿越138均線回測"

# 價格型態
PRICES_W_AT_BUTTOM = "W底"
